In [25]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [26]:
movies = pd.read_csv("../data/TMDB_movie_dataset_v11.csv")

In [27]:
movies.head()

,id,title,vote_average,vote_count,status,release_date,revenue,runtime,adult,backdrop_path,...,original_title,overview,popularity,poster_path,tagline,genres,production_companies,production_countries,spoken_languages,keywords
0,27205,Inception,8.364,34495,Released,2010-07-15,825532764,148,False,/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg,...,Inception,"Cobb, a skilled thief who commits corporate es...",83.952,/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg,Your mind is the scene of the crime.,"Action, Science Fiction, Adventure","Legendary Pictures, Syncopy, Warner Bros. Pict...","United Kingdom, United States of America","English, French, Japanese, Swahili","rescue, mission, dream, airplane, paris, franc..."
1,157336,Interstellar,8.417,32571,Released,2014-11-05,701729206,169,False,/pbrkL804c8yAv3zBZR4QPEafpAR.jpg,...,Interstellar,The adventures of a group of explorers who mak...,140.241,/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg,Mankind was born on Earth. It was never meant ...,"Adventure, Drama, Science Fiction","Legendary Pictures, Syncopy, Lynda Obst Produc...","United Kingdom, United States of America",English,"rescue, future, spacecraft, race against time,..."
2,155,The Dark Knight,8.512,30619,Released,2008-07-16,1004558444,152,False,/nMKdUUepR0i5zn0y1T4CsSB5chy.jpg,...,The Dark Knight,Batman raises the stakes in his war on crime. ...,130.643,/qJ2tW6WMUDux911r6m7haRef0WH.jpg,Welcome to a world without rules.,"Drama, Action, Crime, Thriller","DC Comics, Legendary Pictures, Syncopy, Isobel...","United Kingdom, United States of America","English, Mandarin","joker, sadism, chaos, secret identity, crime f..."
3,19995,Avatar,7.573,29815,Released,2009-12-15,2923706026,162,False,/vL5LR6WdxWPjLPFRLe133jXWsh5.jpg,...,Avatar,"In the 22nd century, a paraplegic Marine is di...",79.932,/kyeqWdyUXW608qlYkRqosgbbJyK.jpg,Enter the world of Pandora.,"Action, Adventure, Fantasy, Science Fiction","Dune Entertainment, Lightstorm Entertainment, ...","United States of America, United Kingdom","English, Spanish","future, society, culture clash, space travel, ..."
4,24428,The Avengers,7.710,29166,Released,2012-04-25,1518815515,143,False,/9BBTo63ANSmhC4e6r62OJFuK2GL.jpg,...,The Avengers,When an unexpected enemy emerges and threatens...,98.082,/RYMX2wcKCBAr24UyPD7xwmjaTn.jpg,Some assembly required.,"Science Fiction, Action, Adventure",Marvel Studios,United States of America,"English, Hindi, Russian","new york city, superhero, shield, based on com..."

In [28]:
movies.shape

(1478019, 24)

In [29]:
movies.columns

Index(['id', 'title', 'vote_average', 'vote_count', 'status', 'release_date',
       'revenue', 'runtime', 'adult', 'backdrop_path', 'budget', 'homepage',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'tagline', 'genres',
       'production_companies', 'production_countries', 'spoken_languages',
       'keywords'],
      dtype='str')

In [30]:
movies.isnull().sum()

id                            0
title                        19
vote_average                  0
vote_count                    0
status                        0
release_date             344013
revenue                       0
runtime                       0
adult                         0
backdrop_path           1116294
budget                        0
homepage                1326672
imdb_id                  796620
original_language             0
original_title               19
overview                 343024
popularity                    0
poster_path              535657
tagline                 1271203
genres                   659758
production_companies     855674
production_countries     726233
spoken_languages         697887
keywords                1117883
dtype: int64

In [31]:
(movies.isnull().sum() / len(movies) * 100).round(2)

id                       0.00
title                    0.00
vote_average             0.00
vote_count               0.00
status                   0.00
release_date            23.28
revenue                  0.00
runtime                  0.00
adult                    0.00
backdrop_path           75.53
budget                   0.00
homepage                89.76
imdb_id                 53.90
original_language        0.00
original_title           0.00
overview                23.21
popularity               0.00
poster_path             36.24
tagline                 86.01
genres                  44.64
production_companies    57.89
production_countries    49.14
spoken_languages        47.22
keywords                75.63
dtype: float64

In [32]:
movies = movies.drop(columns=['homepage'])

In [33]:
movies = movies.drop(columns=['tagline'])

In [34]:
movies_clean = movies.copy()

In [35]:
movies_clean.shape

(1478019, 22)

In [36]:
movies = pd.read_csv("../data/TMDB_movie_dataset_v11.csv")

In [37]:
movies.shape

(1478019, 24)

In [38]:
movies_clean = movies.copy()

In [39]:
movies_clean = movies_clean.drop(columns=['homepage', 'tagline'])

In [40]:
movies_clean.shape

(1478019, 22)

In [41]:
movies_clean['genres'].iloc[0]

'Action, Science Fiction, Adventure'

In [42]:
movies_clean['keywords'].iloc[0]

'rescue, mission, dream, airplane, paris, france, virtual reality, kidnapping, philosophy, spy, allegory, manipulation, car crash, heist, memory, architecture, los angeles, california, dream world, subconscious'

In [43]:
import ast

In [44]:
genres_list = movies_clean['genres'].iloc[0].split(', ')

In [45]:
movies_clean.columns.tolist()

['id',
 'title',
 'vote_average',
 'vote_count',
 'status',
 'release_date',
 'revenue',
 'runtime',
 'adult',
 'backdrop_path',
 'budget',
 'imdb_id',
 'original_language',
 'original_title',
 'overview',
 'popularity',
 'poster_path',
 'genres',
 'production_companies',
 'production_countries',
 'spoken_languages',
 'keywords']

In [46]:
movies_clean[['title', 'genres', 'overview']].head()

,title,genres,overview
0,Inception,"Action, Science Fiction, Adventure","Cobb, a skilled thief who commits corporate es..."
1,Interstellar,"Adventure, Drama, Science Fiction",The adventures of a group of explorers who mak...
2,The Dark Knight,"Drama, Action, Crime, Thriller",Batman raises the stakes in his war on crime. ...
3,Avatar,"Action, Adventure, Fantasy, Science Fiction","In the 22nd century, a paraplegic Marine is di..."
4,The Avengers,"Science Fiction, Action, Adventure",When an unexpected enemy emerges and threatens...

In [47]:
movies_clean['genres'].head()

0             Action, Science Fiction, Adventure
1              Adventure, Drama, Science Fiction
2                 Drama, Action, Crime, Thriller
3    Action, Adventure, Fantasy, Science Fiction
4             Science Fiction, Action, Adventure
Name: genres, dtype: str

In [48]:
movies_clean[['title', 'genres']].head(10)

                     title                                       genres
0                Inception           Action, Science Fiction, Adventure
1             Interstellar            Adventure, Drama, Science Fiction
2          The Dark Knight               Drama, Action, Crime, Thriller
3                   Avatar  Action, Adventure, Fantasy, Science Fiction
4             The Avengers           Science Fiction, Action, Adventure
5                 Deadpool                    Action, Adventure, Comedy
6   Avengers: Infinity War           Adventure, Action, Science Fiction
7               Fight Club                                        Drama
8  Guardians of the Galaxy           Action, Science Fiction, Adventure
9             Pulp Fiction                              Thriller, Crime

In [49]:
movies_clean['keywords'].head()

0    rescue, mission, dream, airplane, paris, franc...
1    rescue, future, spacecraft, race against time,...
2    joker, sadism, chaos, secret identity, crime f...
3    future, society, culture clash, space travel, ...
4    new york city, superhero, shield, based on com...
Name: keywords, dtype: str

In [50]:
movies_clean['overview'] = movies_clean['overview'].fillna('')

In [51]:
movies_clean['overview'].isnull().sum()

np.int64(0)

In [52]:
credits = pd.read_csv("../data/TMDB_movie_dataset_v11.csv")

In [53]:
credits.head()

,id,title,vote_average,vote_count,status,release_date,revenue,runtime,adult,backdrop_path,...,original_title,overview,popularity,poster_path,tagline,genres,production_companies,production_countries,spoken_languages,keywords
0,27205,Inception,8.364,34495,Released,2010-07-15,825532764,148,False,/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg,...,Inception,"Cobb, a skilled thief who commits corporate es...",83.952,/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg,Your mind is the scene of the crime.,"Action, Science Fiction, Adventure","Legendary Pictures, Syncopy, Warner Bros. Pict...","United Kingdom, United States of America","English, French, Japanese, Swahili","rescue, mission, dream, airplane, paris, franc..."
1,157336,Interstellar,8.417,32571,Released,2014-11-05,701729206,169,False,/pbrkL804c8yAv3zBZR4QPEafpAR.jpg,...,Interstellar,The adventures of a group of explorers who mak...,140.241,/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg,Mankind was born on Earth. It was never meant ...,"Adventure, Drama, Science Fiction","Legendary Pictures, Syncopy, Lynda Obst Produc...","United Kingdom, United States of America",English,"rescue, future, spacecraft, race against time,..."
2,155,The Dark Knight,8.512,30619,Released,2008-07-16,1004558444,152,False,/nMKdUUepR0i5zn0y1T4CsSB5chy.jpg,...,The Dark Knight,Batman raises the stakes in his war on crime. ...,130.643,/qJ2tW6WMUDux911r6m7haRef0WH.jpg,Welcome to a world without rules.,"Drama, Action, Crime, Thriller","DC Comics, Legendary Pictures, Syncopy, Isobel...","United Kingdom, United States of America","English, Mandarin","joker, sadism, chaos, secret identity, crime f..."
3,19995,Avatar,7.573,29815,Released,2009-12-15,2923706026,162,False,/vL5LR6WdxWPjLPFRLe133jXWsh5.jpg,...,Avatar,"In the 22nd century, a paraplegic Marine is di...",79.932,/kyeqWdyUXW608qlYkRqosgbbJyK.jpg,Enter the world of Pandora.,"Action, Adventure, Fantasy, Science Fiction","Dune Entertainment, Lightstorm Entertainment, ...","United States of America, United Kingdom","English, Spanish","future, society, culture clash, space travel, ..."
4,24428,The Avengers,7.710,29166,Released,2012-04-25,1518815515,143,False,/9BBTo63ANSmhC4e6r62OJFuK2GL.jpg,...,The Avengers,When an unexpected enemy emerges and threatens...,98.082,/RYMX2wcKCBAr24UyPD7xwmjaTn.jpg,Some assembly required.,"Science Fiction, Action, Adventure",Marvel Studios,United States of America,"English, Hindi, Russian","new york city, superhero, shield, based on com..."

In [54]:
credits.columns

Index(['id', 'title', 'vote_average', 'vote_count', 'status', 'release_date',
       'revenue', 'runtime', 'adult', 'backdrop_path', 'budget', 'homepage',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'tagline', 'genres',
       'production_companies', 'production_countries', 'spoken_languages',
       'keywords'],
      dtype='str')

In [ ]:
def get_top_cast(text):
    data = ast.literal_eval(text)
    return ' '.join(item['name'] for item in data[:3])

In [ ]:
get_top_cast(credits['cast'].iloc[0])

In [ ]:
credits['cast'] = credits['cast'].apply(get_top_cast)

In [ ]:
credits[['title', 'cast']].head()

In [ ]:
credits['crew'].iloc[0]

In [ ]:
def get_director(text):
    data = ast.literal_eval(text)

    for item in data:
        if item['job'] == 'Director':
            return item['name']

    return ''

In [ ]:
get_director(credits['crew'].iloc[0])

In [ ]:
credits['director'] = credits['crew'].apply(get_director)

In [ ]:
credits[['title','cast', 'director']].head()

In [ ]:
movies_clean[['id', 'title']].head()

In [ ]:
credits[['movie_id', 'title']].head()

In [ ]:
movies_clean = movies_clean.merge(
    credits[['movie_id', 'cast', 'director']],
    left_on='id',
    right_on='movie_id'
)

In [ ]:
movies_clean.shape

In [ ]:
movies_clean.columns

In [ ]:
movies_clean = movies_clean.drop(columns=['movie_id'])

In [ ]:
movies_clean.columns

In [ ]:
movies_final = movies_clean[
    ['id', 'title', 'genres', 'keywords', 'overview', 'cast', 'director']
].copy()

In [ ]:
movies_final.head()

In [ ]:
movies_final.isnull().sum()

In [ ]:
movies_clean[['id', 'title']].head()

In [ ]:
credits[['movie_id', 'title']].head()

In [ ]:

movies_final.isnull().sum()

In [ ]:
def remove_space(text):
    return text.replace(" ", "_")

In [ ]:
remove_space("Science Fiction")

In [ ]:
movies_final['genres'] = movies_final['genres'].apply(remove_space)
movies_final['keywords'] = movies_final['keywords'].apply(remove_space)
movies_final['cast'] = movies_final['cast'].apply(remove_space)
movies_final['director'] = movies_final['director'].apply(remove_space)

In [ ]:
movies_final[['title', 'genres', 'keywords', 'cast', 'director']].head()

In [ ]:
movies_final['tags'] = (
    movies_final['genres'] + " " +
    movies_final['keywords'] + " " +
    movies_final['overview'] + " " +
    movies_final['cast'] + " " +
    movies_final['director']
)

In [ ]:
movies_final[['title', 'tags']].head()

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [ ]:
tfidf = TfidfVectorizer(
    max_features=5000,
    stop_words='english'
)

In [ ]:
tfidf_matrix = tfidf.fit_transform(movies_final['tags'])

In [ ]:
tfidf_matrix.shape

In [ ]:
len(tfidf.get_feature_names_out())

In [ ]:
tfidf.get_feature_names_out()[:20]

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity

In [ ]:
similarity = cosine_similarity(
    tfidf_matrix,
    tfidf_matrix
)

In [ ]:
similarity.shape

In [ ]:
similarity[0][:10]

In [ ]:
similarity[0].shape

In [ ]:
movies_final[['title']].head(10)

In [ ]:
movies_final.iloc[0]['title']

In [ ]:
similar_movies = list(enumerate(similarity[0]))

In [ ]:
similar_movies = sorted(
    similar_movies,
    key=lambda x: x[1],
    reverse=True
)

In [ ]:
similar_movies[:10]

In [ ]:
for index, score in similar_movies[:10]:
    print(movies_final.iloc[index]['title'], score)

In [ ]:
def recommend(movie_title):
    
    movie_index = movies_final[
        movies_final['title'].str.lower() == movie_title.lower()
    ].index[0]
    
    similarity_scores = list(
        enumerate(similarity[movie_index])
    )
    
    similarity_scores = sorted(
        similarity_scores,
        key=lambda x: x[1],
        reverse=True
    )
    
    print(f"Recommendations for: {movie_title}\n")
    
    for index, score in similarity_scores[1:11]:
        print(f"{movies_final.iloc[index]['title']} - {score:.3f}")

In [ ]:
recommend("Avatar")

In [ ]:
def recommend(movie_title, n=10):
    
    # پیدا کردن فیلم
    matches = movies_final[
        movies_final['title'].str.lower().str.strip()
        == movie_title.lower().strip()
    ]
    
    if matches.empty:
        print(f"Movie '{movie_title}' not found.")
        return
    
    movie_index = matches.index[0]
    
    # گرفتن similarity
    similarity_scores = list(
        enumerate(similarity[movie_index])
    )
    
    # مرتب کردن از بیشترین شباهت به کمترین
    similarity_scores = sorted(
        similarity_scores,
        key=lambda x: x[1],
        reverse=True
    )
    
    print(f"\nRecommendations for: {movie_title}\n")
    
    # حذف خود فیلم
    for index, score in similarity_scores[1:n+1]:
        title = movies_final.iloc[index]['title']
        print(f"{title} - similarity: {score:.3f}")

In [ ]:
recommend("Avatar")

In [ ]:
recommend("The Dark Knight", 10)

In [ ]:
def recommend(movie_title, n=10):
    # پیدا کردن فیلم
    matches = movies_final[
        movies_final['title'].str.lower() == movie_title.lower()
    ]

    if matches.empty:
        return f"Movie '{movie_title}' not found."

    movie_index = matches.index[0]

    # گرفتن similarity مربوط به فیلم
    similarity_scores = list(
        enumerate(similarity[movie_index])
    )

    # مرتب‌سازی بر اساس بیشترین شباهت
    similarity_scores = sorted(
        similarity_scores,
        key=lambda x: x[1],
        reverse=True
    )

    # حذف خود فیلم
    similarity_scores = similarity_scores[1:n+1]

    # گرفتن index فیلم‌ها
    movie_indices = [x[0] for x in similarity_scores]

    # ساخت نتیجه
    recommendations = movies_final.iloc[movie_indices][
        ['title']
    ].copy()

    recommendations['similarity'] = [
        round(x[1], 3)
        for x in similarity_scores
    ]

    return recommendations.reset_index(drop=True)

In [ ]:
recommend("Oppenheimer",5)

In [ ]:
def search_movies(query):
    results = movies_final[
        movies_final['title'].str.contains(
            query,
            case=False,
            na=False
        )
    ]

    return results[['title']].reset_index(drop=True)

In [ ]:
search_movies("star")

In [ ]:
from difflib import get_close_matches

In [ ]:
def find_similar_movies(query, limit=10, cutoff=0.5):
    titles = movies_final['title'].tolist()

    matches = get_close_matches(
        query,
        titles,
        n=limit,
        cutoff=cutoff
    )

    return matches

In [ ]:
def smart_recommend(query, n=10):
    # پیدا کردن فیلم‌هایی که دقیقاً با عبارت واردشده مطابقت دارند
    exact_matches = movies_final[
        movies_final['title'].str.lower() == query.lower()
    ]

    # اگر فیلم دقیقاً پیدا شد
    if not exact_matches.empty:
        movie_title = exact_matches.iloc[0]['title']

        print(f"Movie found: {movie_title}")

        return recommend(movie_title, n)

    # اگر فیلم دقیق پیدا نشد، جستجوی تقریبی انجام می‌دهیم
    similar_titles = find_similar_movies(query, limit=5)

    if not similar_titles:
        return "No similar movies found."

    print("Movie not found exactly")
    print("Did you mean one of these?")

    for i, title in enumerate(similar_titles, start=1):
        print(f"{i}. {title}")

    return None

In [ ]:
def smart_recommend(query, n=10):
    # جستجوی دقیق
    exact_matches = movies_final[
        movies_final['title'].str.lower() == query.lower()
    ]

    if not exact_matches.empty:
        movie_title = exact_matches.iloc[0]['title']

        print(f"فیلم پیدا شد: {movie_title}")

        return recommend(movie_title, n)

    # جستجوی تقریبی
    similar_titles = find_similar_movies(query, limit=5)

    if not similar_titles:
        return "No similar movies found."

    # بهترین تطابق
    best_match = similar_titles[0]

    print(f"'{query}' پیدا نشد.")
    print(f"مشابه ترین کلمه: {best_match}")

    return recommend(best_match, n)

In [ ]:
smart_recommend("incepton", 5)

In [ ]:
import pandas as pd

movies = pd.read_csv("../data/TMDB_movie_dataset_v11.csv")

movies.head()

In [ ]:
movies.shape

In [ ]:
movies_clean['genres'] = movies_clean['genres'].fillna('')
movies_clean['keywords'] = movies_clean['keywords'].fillna('')
movies_clean['overview'] = movies_clean['overview'].fillna('')

In [ ]:
movies_clean['genres'] = movies_clean['genres'].str.replace(',', ' ', regex=False)
movies_clean['keywords'] = movies_clean['keywords'].str.replace(',', ' ', regex=False)

In [57]:
movies_clean['tags'] = (
    movies_clean['genres'] + ' ' +
    movies_clean['keywords'] + ' ' +
    movies_clean['overview']
)

In [56]:
movies_clean[['title', 'tags']].head()

KeyError: "['tags'] not in index"

In [58]:
movies_clean.columns.tolist()

['id',
 'title',
 'vote_average',
 'vote_count',
 'status',
 'release_date',
 'revenue',
 'runtime',
 'adult',
 'backdrop_path',
 'budget',
 'imdb_id',
 'original_language',
 'original_title',
 'overview',
 'popularity',
 'poster_path',
 'genres',
 'production_companies',
 'production_countries',
 'spoken_languages',
 'keywords',
 'tags']

In [59]:
movies_clean[['title', 'genres', 'keywords', 'overview', 'tags']].head()

,title,genres,keywords,overview,tags
0,Inception,"Action, Science Fiction, Adventure","rescue, mission, dream, airplane, paris, franc...","Cobb, a skilled thief who commits corporate es...","Action, Science Fiction, Adventure rescue, mis..."
1,Interstellar,"Adventure, Drama, Science Fiction","rescue, future, spacecraft, race against time,...",The adventures of a group of explorers who mak...,"Adventure, Drama, Science Fiction rescue, futu..."
2,The Dark Knight,"Drama, Action, Crime, Thriller","joker, sadism, chaos, secret identity, crime f...",Batman raises the stakes in his war on crime. ...,"Drama, Action, Crime, Thriller joker, sadism, ..."
3,Avatar,"Action, Adventure, Fantasy, Science Fiction","future, society, culture clash, space travel, ...","In the 22nd century, a paraplegic Marine is di...","Action, Adventure, Fantasy, Science Fiction fu..."
4,The Avengers,"Science Fiction, Action, Adventure","new york city, superhero, shield, based on com...",When an unexpected enemy emerges and threatens...,"Science Fiction, Action, Adventure new york ci..."

In [60]:
movies_clean['tags'] = movies_clean['tags'].fillna('').astype(str)

movies_clean['tags'] = movies_clean['tags'].str.lower()

movies_clean[['title', 'tags']].head()

             title                                               tags
0        Inception  action, science fiction, adventure rescue, mis...
1     Interstellar  adventure, drama, science fiction rescue, futu...
2  The Dark Knight  drama, action, crime, thriller joker, sadism, ...
3           Avatar  action, adventure, fantasy, science fiction fu...
4     The Avengers  science fiction, action, adventure new york ci...

In [61]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(
    stop_words='english',
    max_features=10000
)

tfidf_matrix = tfidf.fit_transform(movies_clean['tags'])

In [62]:
tfidf_matrix.shape

(1478019, 10000)